### ISSUE TITLE
Issues when trying to use jest-circus with custom env

### ISSUE THREAD

**Issue by ernestorocha** [gribnoysup/setup-polly-jest#17]
Hi,

I'm having some problems trying to use your package with `jest-circus` and `setup-polly-jest/jest-environment-node`.

I followed the instructions and tried a few things without success.

I'm using a fairly updated packages, as you can see here:
```    "@pollyjs/core": "^4.0.4",
    "jest": "^26.1.0",
    "jest-circus": "^26.1.0",
    "setup-polly-jest": "^0.9.0"
```

But when I try to run any existing test I get this message:
```
● Validation Error:

  Test environment setup-polly-jest/jest-environment-node cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

I'm not quite sure why, but I think the module `setup-polly-jest/jest-environment-node` is not being exposed properly or maybe not published?

This is the current folder tree of the `node_modules/setup-polly-jest`:

```
.
├── LICENSE
├── README.md
├── index.js
├── lib
│   ├── common.js
│   ├── jasmine.js
│   ├── jest-circus.js
│   └── jest-environment-polly.js
└── package.json
```

Thanks for any help and thank you very much for this package.

**Comment by gribnoysup** [comment]
Hi @ernestorocha, thanks for reporting! Seems like I forgot to include those new env files  to the published assets with the latest release 🤦 Will fix ASAP

**Comment by gribnoysup** [comment]
Should be fixed now! Can you please try with `setup-polly-jest@0.9.1`?

**Comment by ernestorocha** [comment]
Yes, I just tired and seems to be working fine. Although I could not test properly because `jest-circus` is complaining about some other stuff.

Thanks for the quick fix!

**Comment by gribnoysup** [comment]
Good to know! I'm closing for now, but if something else is not working well with circus, feel free to open another issue
