### ISSUE TITLE
Customise <Recording Name>?

### ISSUE THREAD

**Issue by miloss** [gribnoysup/setup-polly-jest#21]
Hi Sergey,

First of all - thank you for maintaining this! I am trying to use Polly with this setup, in a "replay" mode only, and want to choose which file(s) to serve per specific test case. From what I see, `<Recording Name>` is being set here:
```js
let recordingName = getRecordingName(spec, specParentSuite, topSuite);
globals.pollyContext.polly = new PollyConstructor(recordingName, globals.pollyContext.options);
```

Is it possible to change anyhow the name of current "Polly instance" name, in the test run? For example, on the top of each test case, or maybe in `beforeEach`. If not, would you consider that as a feature, and can you imagine how the preferred API would look like?

Many thanks,

Milos

**Comment by gribnoysup** [comment]
Hi @miloss, I'm not sure if it's documented anywhere, but looking at pollyjs source, seems like they allow to override the recording name by reassigning it directly on the polly instance:

```js
const polly = new Polly('a');
polly.recordingName = 'b'
```

See [this test case](https://github.com/Netflix/pollyjs/blob/c4648ffeea9b0cd0647f5271bbb22406e1bed757/packages/%40pollyjs/core/tests/unit/polly-test.js#L50-L60 ) for an example. But fair warning I never tried it so am not sure how this affects Polly behavior and if this will solve your case.

Providing a configuration option in this helper to change recording name feels like out of scope for me as the main reason for this helper to exist is allow you easily create separate records per test case, so maybe in your scenario you will benefit from creating polly instance manually without using this test helper at all.

**Comment by miloss** [comment]
Thank you @gribnoysup for reply and support. You are right, overriding `.recordingName` directly on the instance seemed to work. At the end I've opted for manually creating polly instance, and it seems to work as expected.

Thank you again for this library, I was able to save much time in setting it up and running.
