### ISSUE TITLE
Triggers Jasmine deprecation

### ISSUE THREAD

**Issue by alanpoulain** [gribnoysup/setup-polly-jest#22]
Since Jasmine 3.7.0, using `setup-polly-jest` triggers the following deprecation:
```
DEPRECATION: An asynchronous before/it/after function was defined with the async keyword but also took a done callback. This is not supported and will stop working in the future. Either remove the done callback (recommended) or remove the async keyword.
```

It's probably because of:
https://github.com/gribnoysup/setup-polly-jest/blob/13db62ea1503b4ff61215f5a3c4d1bbd8de0d03d/src/jasmine.js#L96

Since the `before` and `after` proxies have the `done` callback and are also asynchronous.

**Comment by gribnoysup** [comment]
Hey @alanpoulain! Thanks for the report and sorry that it took awhile to get to it, the issue should be fixed in the latest release

**Comment by alanpoulain** [comment]
Nice, thank you for your work!
