### ISSUE TITLE
Remove numbers from suite/test names

### ISSUE THREAD

**Issue by stephenh** [gribnoysup/setup-polly-jest#7]
Currently using `setup-polly-jest` in a node environment I'm getting folder names like `__recordings/SomeSuite-1234567890/test-abc-234578901`. Is there a way to remove the numbers? 

I briefly looked at the source and I'm not sure if its `setup-polly-jest` or jest itself or polly that is introducing these, but just thought I'd naively ask.

**Comment by gribnoysup** [comment]
AFAIU this behavior comes from PollyJS persister logic: when persisting the recording, special `recordingId` is used to save the `har` file. You can see the logic for this id generation here: https://github.com/Netflix/pollyjs/blob/02a476716d67225195842fe7ef92fac6dc383041/packages/%40pollyjs/core/src/utils/guid-for-recording.js#L19-L24

I don't know if you can change this behavior or not, I would suggest to ask in the PollyJS repository about that

**Comment by stephenh** [comment]
Great, thanks! I'll follow up there.

**Comment by gribnoysup** [comment]
Just in case someone else will be wondering, here's the issue in PollyJS repo: https://github.com/Netflix/pollyjs/issues/252#issuecomment-531577983
