### ISSUE TITLE
Feature req: add current context

### ISSUE THREAD

**Issue by buratinodev** [gribnoysup/setup-polly-jest#9]
It would be ince if we could do something like this: 
` describe('test auth failure handling', () => {
      setupPolly({
        adapters: ['node-http'],
        persister: 'fs',
        timing: Timing.fixed(api.FETCH_TIMEOUT+1000),
        persisterOptions: {
          fs: {
            recordingsDir: path.resolve(__dirname, '../__recordings__')
          }
        }
      });

      it('test auth failure on timeout and read from cookie ', async () => {
        const storedJwt = getCookie('jwt_token');
        const jwt = await api.auth('');
        expect(storedJwt).toEqual(jwt);
      }, api.FETCH_TIMEOUT + 1500)
    })`

**Comment by gribnoysup** [comment]
Hi @javahaxxor! I'm not exactly sure what feature are you asking for. Can you provide more details? Maybe an _expected_ and _current_ behavior examples?

**Comment by buratinodev** [comment]
Mental note: don't open issues when i'm tired and can't get my stuff to work :)
Sorry @gribnoysup
